### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by norvegec** [Eveneum/Sample#2]
I'm very new to event sourcing. Cloned the sample fo
I think I'm missing some points here:

1. What is the purpose to have dedicated DocumentType "Header"?
2. Is snapshot something like persisted materialized view? What is the difference between those concepts?
3. Why snapshots are stored in the same collection?

**Comment by jkonecki** [comment]
Hello DIma!

RE 1: Stream header defines common data and metadata for the whole stream. It is also used for optimistic concurrency checks as it maintains the stream version.

RE 2: Yes, you con think about snapshots as materialized views of the stream as of a certain version. You can have multiple snapshots at different versions. Snapshots are mainly used as a performance tool - for a very long streams it may not be feasible to read all the events from the very beginning. 

RE 3: Why shouldn't they? You wouldn't store your materailized views in a different SQL database than your tables on which the views are based. Also, introducing a separate collection in CosmosDB may incur an additional cost..

I would recommend you watch the below video that will answer your question in greater detail:
https://www.youtube.com/watch?v=8JKjvY4etTY

You might want to search for other Greg Young presentations on Event Sourcing and CQRS.
